// 6개 시안 공통 더미 이벤트 데이터
// 각 HTML 시안에서 <script src="_shared/seed-data.js"></script>로 로드하거나
// self-contained가 필요하면 인라인 복사해서 사용한다.

window.SEED_EVENTS = [
  {
    id: 'e1',
    title: '신라면 블랙 출시 기념 댓글 이벤트 — 1000명 추첨',
    platform: '인스타그램',
    status: 'ready',
    resultStatus: 'unknown',
    receiptStatus: 'unclaimed',
    deadlineText: '오늘마감',
    deadlineDate: '2026-05-18',
    prizeText: '신라면 블랙 1박스 + 컵라면 세트',
    prizeAmount: '2만원',
    totalWinnerCount: 1000,
    applyUrl: 'https://instagram.com/p/example1',
    source: '인스타그램 · @nongshim_kr',
    image: 'https://picsum.photos/seed/ramen/600/400'
  },
  {
    id: 'e2',
    title: '갤럭시 S26 사전예약 응모 — 100명 추첨',
    platform: '카카오톡',
    status: 'ready',
    resultStatus: 'unknown',
    receiptStatus: 'unclaimed',
    deadlineText: '내일마감',
    deadlineDate: '2026-05-19',
    prizeText: '갤럭시 S26 Ultra 256GB',
    prizeAmount: '180만원',
    totalWinnerCount: 100,
    applyUrl: 'https://example.com/galaxy',
    source: '카카오톡 · 삼성전자 채널',
    image: 'https://picsum.photos/seed/galaxy/600/400'
  },
  {
    id: 'e3',
    title: '스타벅스 신메뉴 시음 이벤트',
    platform: '유튜브',
    status: 'ready',
    resultStatus: 'unknown',
    receiptStatus: 'unclaimed',
    deadlineText: '마감 5월 22일',
    deadlineDate: '2026-05-22',
    prizeText: '스타벅스 e-기프트카드 3만원권',
    prizeAmount: '3만원',
    totalWinnerCount: 500,
    applyUrl: 'https://example.com/sbux',
    source: '유튜브 · 스타벅스코리아',
    image: 'https://picsum.photos/seed/coffee/600/400'
  },
  {
    id: 'e4',
    title: '여름맞이 다이슨 에어랩 증정 이벤트',
    platform: '인스타그램',
    status: 'later',
    resultStatus: 'unknown',
    receiptStatus: 'unclaimed',
    deadlineText: '마감 5월 31일',
    deadlineDate: '2026-05-31',
    prizeText: '다이슨 에어랩 컴플리트',
    prizeAmount: '69만원',
    totalWinnerCount: 3,
    applyUrl: 'https://example.com/dyson',
    source: '인스타그램 · @beauty_kr',
    image: 'https://picsum.photos/seed/dyson/600/400'
  },
  {
    id: 'e5',
    title: '맥북 프로 M5 출시기념 응모 이벤트',
    platform: '기타',
    status: 'done',
    resultStatus: 'won',
    receiptStatus: 'received',
    deadlineText: '마감 4월 30일',
    deadlineDate: '2026-04-30',
    resultAnnouncementDate: '2026-05-10',
    resultAnnouncementText: '결과발표 5월 10일',
    prizeText: '맥북 프로 14인치 M5',
    prizeAmount: '299만원',
    prizeTitle: '맥북 프로 14',
    totalWinnerCount: 5,
    participatedAt: '2026-04-28',
    winningMemo: '5월 12일 수령 완료, 시리얼 C02XX',
    source: '기타 · 애플 공식',
    image: 'https://picsum.photos/seed/macbook/600/400'
  },
  {
    id: 'e6',
    title: '봄맞이 백화점 상품권 추첨',
    platform: '카카오톡',
    status: 'done',
    resultStatus: 'won',
    receiptStatus: 'unclaimed',
    deadlineText: '마감 5월 5일',
    deadlineDate: '2026-05-05',
    resultAnnouncementDate: '2026-05-18',
    resultAnnouncementText: '오늘 발표',
    prizeText: '신세계 상품권 10만원권',
    prizeAmount: '10만원',
    totalWinnerCount: 50,
    participatedAt: '2026-05-03',
    source: '카카오톡 · 신세계백화점',
    image: 'https://picsum.photos/seed/voucher/600/400'
  },
  {
    id: 'e7',
    title: '러닝화 신제품 체험단 모집',
    platform: '인스타그램',
    status: 'done',
    resultStatus: 'lost',
    receiptStatus: 'unclaimed',
    deadlineText: '마감 4월 20일',
    deadlineDate: '2026-04-20',
    resultAnnouncementDate: '2026-05-01',
    prizeText: '나이키 페가수스 41',
    prizeAmount: '16만원',
    totalWinnerCount: 30,
    participatedAt: '2026-04-15',
    source: '인스타그램 · @nike_kr',
    image: 'https://picsum.photos/seed/shoes/600/400'
  },
  {
    id: 'e8',
    title: '편의점 도시락 신메뉴 댓글 이벤트',
    platform: '유튜브',
    status: 'ready',
    resultStatus: 'unknown',
    receiptStatus: 'unclaimed',
    deadlineText: '오늘마감',
    deadlineDate: '2026-05-18',
    prizeText: 'CU 모바일 상품권 5천원권',
    prizeAmount: '5천원',
    totalWinnerCount: 2000,
    applyUrl: 'https://example.com/cu',
    source: '유튜브 · CU공식',
    image: 'https://picsum.photos/seed/lunchbox/600/400'
  }
];

window.PLATFORM_META = {
  '인스타그램': { color: '#e1306c', emoji: '📷' },
  '유튜브':    { color: '#ff0000', emoji: '▶️' },
  '카카오톡':   { color: '#fee500', emoji: '💬' },
  '기타':      { color: '#94a0b6', emoji: '🔗' }
};
